- name: Set-top Box
  hosts: all
  tasks:
    - name: Install lxml
      ansible.builtin.dnf:
        name: python3-lxml
      become: true

    - name: Add RPM Fusion keys
      ansible.builtin.rpm_key:
        key: "{{ item }}"
      become: true
      loop:
        - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020"

    - name: Add RPM Fusion repository
      ansible.builtin.dnf:
        name:
          - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
      become: true

    - name: Install dnf-automatic
      ansible.builtin.dnf:
        name: dnf-automatic
      become: true

    - name: Configure automatic updates to download and install
      community.general.ini_file:
        path: /etc/dnf/automatic.conf
        section: commands
        option: apply_updates
        value: "yes"
        owner: root
        group: root
        mode: "0644"
      become: true

    - name: Enable and start automatic update timer
      ansible.builtin.systemd:
        name: dnf-automatic.timer
        enabled: true
        state: started
      become: true

    - name: Enable GDM automatic login
      community.general.ini_file:
        path: /etc/gdm/custom.conf
        section: daemon
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        no_extra_spaces: true
        owner: root
        group: root
        mode: "0644"
      loop:
        - option: AutomaticLoginEnable
          value: "True"
        - option: AutomaticLogin
          value: "{{ ansible_facts['user_id'] }}"
      become: true

    - name: Desktop settings
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - key: /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type
          value: "'nothing'"
        - key: /org/gnome/desktop/session/idle-delay
          value: uint32 0

    - name: Install Deluge
      ansible.builtin.dnf:
        name: deluge-daemon
      become: true

    - name: Start Deluge
      ansible.builtin.systemd_service:
        name: deluge-daemon
        enabled: true
        state: started
      become: true

    - name: Create Deluge directory
      ansible.builtin.file:
        path: /var/lib/deluge/Downloads
        state: directory
        owner: deluge
        group: deluge
        mode: "0755"
      become: true

    - name: Allow remote connections
      ansible.builtin.command:
        cmd: deluge-console config --set allow_remote true
      become: true
      become_user: deluge

    - name: Restart Deluge
      ansible.builtin.systemd_service:
        name: deluge-daemon
        state: restarted
      become: true

    - name: Link Deluge directory
      ansible.builtin.file:
        path: "{{ ansible_facts['env']['HOME'] }}/deluge"
        src: /var/lib/deluge/Downloads
        state: link

    - name: Configure Deluge authentication
      ansible.builtin.lineinfile:
        path: /var/lib/deluge/.config/deluge/auth
        regexp: "^jon:"
        line: "jon:jon:10"
      become: true

    - name: Generate SSH keys
      ansible.builtin.user:
        name: "{{ ansible_facts['user_id'] }}"
        generate_ssh_key: true

    - name: Install packages
      ansible.builtin.dnf:
        name: kodi
      become: true

    - name: Create Kodi directories
      ansible.builtin.file:
        path: "{{ ansible_facts['env']['HOME'] }}/{{ item }}"
        state: directory
        owner: "{{ ansible_facts['user_id'] }}"
        group: "{{ ansible_facts['user_gid'] }}"
        mode: "0755"
      loop:
        - Movies
        - TV Shows

    - name: Create XDG autostart directory
      ansible.builtin.file:
        path: "{{ ansible_facts['env']['HOME'] }}/.config/autostart"
        state: directory
        owner: "{{ ansible_facts['user_id'] }}"
        group: "{{ ansible_facts['user_gid'] }}"
        mode: "0755"

    - name: Configure Kodi to start automatically
      ansible.builtin.copy:
        src: /usr/share/applications/kodi.desktop
        dest: "{{ ansible_facts['env']['HOME'] }}/.config/autostart/kodi.desktop"
        remote_src: true
        owner: "{{ ansible_facts['user_id'] }}"
        group: "{{ ansible_facts['user_gid'] }}"
        mode: "0644"
